apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: backend
  name: backend
  namespace: strelka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: backend
    spec:
      volumes:
        - name: yara-rules
          hostPath:
            path: /tmp/backend
            type: DirectoryOrCreate
      initContainers:
        - name: download-yara-rules
          image: python:3.12-slim
          command:
            - sh
            - -c
            - |
              ls -la
              pwd
              cd /yara-rules

              if [ -f "rules.yar" ]; then
                echo "YARA rules already exist in /yara-rules. Skipping download!"
                exit 0
              fi

              apt-get update && apt-get install -y unzip 
              pip install --no-cache-dir gdown 
              gdown "https://drive.google.com/file/d/1NUxzuzkM4Bn90f8gjblmS3wdE8CTU14-/view?usp=sharing"
              unzip *.zip
              pwd
              whoami
              mv content/drive/MyDrive/YARA/rules/* .
              ls -la
              rm -rf content
              rm *.zip
          volumeMounts:
            - name: yara-rules
              mountPath: /yara-rules
      containers:
        - args:
            - strelka-backend
          image: target/strelka-backend:latest
          name: backend
          volumeMounts:
            - mountPath: /etc/strelka/
              name: yara-rules
              readOnly: true

      restartPolicy: Always
      
