apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: jaeger
  name: jaeger
  namespace: strelka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
        - env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          image: jaegertracing/all-in-one:1.42
          name: jaeger
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: jaeger
  name: jaeger
  namespace: strelka
spec:
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: agent-thrift
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: jaeger-thrift
      port: 14268
      targetPort: 14268
  selector:
    io.kompose.service: jaeger
