import json
from typing import Optional

from utils import vt_lookup


def analyze_file_type(
    file_json: dict,
    depth: int,
    extension: str,
    parent_extension: str = None
) -> dict:

    # Canonical definitions
    CANONICAL_TYPES = {
        "office_doc": {
            "doc", "docx", "docm",
            "xls", "xlsx", "xlsm",
            "ppt", "pptx", "office_doc"
        },
        "pdf": {"pdf"},
        "archive": {"zip", "rar", "7z", "tar", "gz", "archive"},
        "executable": {"executable", "exe", "dll", "elf", "macho"},
        "script": {"script", "js", "vbs", "ps1", "bat", "sh"},
        "image": {"image", "png", "jpg", "jpeg", "gif", "bmp", "heic"},
        "text": {"image", "txt", "csv"}
    }

    EXTENSION_TO_TYPE = {
        ext: category
        for category, exts in CANONICAL_TYPES.items()
        for ext in exts
    }

    EXPECTED_CHILDREN = {
        "office_doc": {"xml", "image", "rels", "ole", "png", "jpg", "jpeg", "gif", "bmp", "heic"},
        "pdf": {"image", "font", "text", "png", "jpg", "jpeg", "gif", "bmp", "heic", "txt", "csv"},
        "archive": {"office_doc", "pdf", "image", "text", "png", "jpg", "jpeg", "gif", "bmp", "heic", "txt", "csv"},
        "image": set()
    }


    extension = extension.lower() if extension else None
    file_type = EXTENSION_TO_TYPE.get(extension, "unknown")

    mime = file_json.get("mime", [])
    yara = file_json.get("yara", [])

    # Root file logic
    if depth == 0:
        classification = "Unusual"

        if (
            any(file_type in m for m in mime) or
            any(file_type in y for y in yara) or
            any(extension in m for m in mime) or
            any(extension in y for y in yara)
        ):
            classification = "Normal"

        return mime, classification


    # Child file logic
    classification = "Unusual"
    parent_extension = EXTENSION_TO_TYPE.get(parent_extension, "unknown")
    expected = EXPECTED_CHILDREN.get(parent_extension, set())

    for m in mime:
        for e in expected:
            if e in m:
                classification = "Normal"

    for m in yara:
        for e in expected:
            if e in m:
                classification = "Normal"

    if extension in expected or file_type in expected:
        classification = "Normal"

    return mime, classification



def get_extension(filename: str) -> Optional[str]:
    if "." not in filename:
        return None
    return filename.rsplit(".", 1)[-1].lower()



def analyze_iocs(iocs: list) -> tuple[int, list[str]]:
    score = 0
    reasons = []

    suspicious_tlds = {
        ".tk", ".ml", ".ga", ".cf", ".gq",
        ".xyz", ".buzz", ".top", ".loan", ".bond",
        ".faith", ".stream", ".download", ".online",
        ".tech", ".work", ".country", ".kim",
        ".science", ".ninja", ".date", ".racing",
        ".cricket", ".win", ".space", ".accountant",
        ".realtor", ".christmas", ".gdn", ".men", ".pro", ".click", ".site"
    }

    for item in iocs:
        ioc = item.get("ioc", "")
        ioc_type = item.get("ioc_type", "")

        if ioc_type in {"url", "domain"}:
            score += 5
            for tld in suspicious_tlds:
                if tld in ioc:
                    score += 20
                    reasons.append(f"Suspicious TLD detected: {tld}")

        if ioc_type == "ip":
            score += 30
            reasons.append("IP exist in the file")

    vt_result = vt_lookup(ioc, ioc_type)

    if vt_result:
        if vt_result["malicious"] > 0:
            score += 100
            reasons.append(
                f"VirusTotal malicious IOC: {ioc} "
                f"(detections: {vt_result['malicious']})"
            )
        elif vt_result["suspicious"] > 1:
            score += 50
            reasons.append(
                f"VirusTotal suspicious IOC: {ioc}"
            )

    return score, reasons


def check_automated_files(creator):

    HIGH_RISK_CREATORS = {
        "headless", "puppeteer", "playwright", "selenium", "chromium"
    }

    PDF_ENGINES = {
        "skia", "pdfium", "wkhtmltopdf", "weasyprint",
        "prince", "pdfkit", "reportlab"
    }

    SCRIPT_TOOLS = {
        "libreoffice", "openoffice", "unoconv",
        "pandoc", "ghostscript"
    }
    score = 0
    creator = creator.lower()
    reasons = []
    if any(k in creator for k in HIGH_RISK_CREATORS):
        score += 40
        reasons.append(f"Document generated by automated browser: {creator}")

    elif any(k in creator for k in PDF_ENGINES):
        score += 30
        reasons.append(f"Programmatic PDF generator detected: {creator}")

    elif any(k in creator for k in SCRIPT_TOOLS):
        score += 20
        reasons.append(f"Document generated via scripting tool: {creator}")

    return score, reasons


def check_yara(yara_out):
    matches = yara_out.get("matches", [])
    score = 0
    reasons = []
    if matches:
        for rule in matches:
            score += 30
            reasons.append(f"yara rule fired: {rule}")

    return score, reasons



def compute_score(strelka_json, file_path):

    score = 0
    reasons = []
    verdict = "Benign"
    extension = get_extension(file_path)
    for jsn in strelka_json:
        depth = jsn.get("file", {}).get("depth")
        if depth == 0:
            file_type, classification = analyze_file_type(jsn.get("file", {}).get("flavors", {}), depth, extension)
            if classification == "Unusual":
                score = score + 50
                reasons.append(f"Umatched file type, original: {extension}, detected: {file_type}")
        else:
            file_type, classification = analyze_file_type(jsn.get("file", {}).get("flavors", {}), depth, extension, extension)
            if classification == "Unusual":
                score = score + 50
                reasons.append(f"Umatched file type included, parent: {extension}, detected: {file_type}")

        mime = jsn.get("file", {}).get("flavors", {}).get("mime", [])
        yara = jsn.get("file", {}).get("flavors", {}).get("yara", [])

        for m in mime:
            if "encrypted" in m:
                score += 50
                reasons.append("Encrypted file")
        for m in yara:
            if "encrypted" in m:
                score += 50
                reasons.append("Encrypted file")

        clamav_scan = jsn.get("scan", {}).get("clamav", {})

        infected_raw = clamav_scan.get("Infected files", "0")

        try:
            infected = int(infected_raw)
        except (ValueError, TypeError):
            infected = 0

        if infected > 0:
            score += 100
            reasons.append("ClamAV detected malware signature")

        entropy = jsn.get("scan", {}).get("entropy", {}).get("entropy")

        if entropy > 7.2:
            score += 25
            if entropy > 7.8:
                score += 10
            reasons.append(f"High entropy = {entropy}")

        if jsn.get("iocs", []):
            s, r = analyze_iocs(jsn.get("iocs", []))
            score += s
            for u in r:
                if u not in reasons:
                    reasons.append(u)

        if jsn.get("scan", {}).get("exiftool", {}).get("creator"):
            s, r = check_automated_files(jsn.get("scan", {}).get("exiftool", {}).get("creator"))
            score += s
            for u in r:
                reasons.append(u)

        if jsn.get("scan", {}).get("exiftool", {}).get("producer"):
            s, r = check_automated_files(jsn.get("scan", {}).get("exiftool", {}).get("producer"))
            score += s
            for u in r:
                reasons.append(u)

        if jsn.get("scan", {}).get("yara", {}):
            s, r = check_yara(jsn.get("scan", {}).get("yara", {}))
            score += s
            if r:
                for u in r:
                    reasons.append(u)

        if jsn.get("pdf", {}).get("yara", {}):
            s, r = check_yara(jsn.get("pdf", {}).get("yara", {}))
            score += s
            if r:
                for u in r:
                    reasons.append(u)

    if score >= 50:
        verdict = "Malicious"

    return score, verdict, reasons
