apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: backend
  name: backend
  namespace: strelka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../strelka/build/docker-compose-no-build.yaml --provider kubernetes convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - strelka-backend
          image: target/strelka-backend:latest
          name: backend
          volumeMounts:
            - mountPath: /etc/strelka/
              name: yara-rules
              readOnly: true

      restartPolicy: Always
      volumes:
        - name: yara-rules
          hostPath:
            path: /data/backend
            type: Directory
