name: Test docker image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: build app.py
        run: |
          python build app.py

      - name: Download roles files
        run: |
          chmod +x downloadRoles.sh
          ./downloadRoles.sh

      - name: Run compose up
        run: |
          docker compose up -d --wait
          docker images
